
package com.yitian.ldh.webservice.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UserWebServiceImpl", targetNamespace = "http://soap.webservice.ldh.yitian.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UserWebServiceImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.yitian.ldh.webservice.soap.User
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findUserByLoginName", targetNamespace = "http://soap.webservice.ldh.yitian.com/", className = "com.yitian.ldh.webservice.soap.FindUserByLoginName")
    @ResponseWrapper(localName = "findUserByLoginNameResponse", targetNamespace = "http://soap.webservice.ldh.yitian.com/", className = "com.yitian.ldh.webservice.soap.FindUserByLoginNameResponse")
    @Action(input = "http://soap.webservice.ldh.yitian.com/UserWebServiceImpl/findUserByLoginNameRequest", output = "http://soap.webservice.ldh.yitian.com/UserWebServiceImpl/findUserByLoginNameResponse")
    public User findUserByLoginName(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

}
